# Form implementation generated from reading ui file 'main_interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Task Tracker")
        Form.resize(1100, 842)
        self.current_date_information = QtWidgets.QLineEdit(parent=Form)
        self.current_date_information.setGeometry(QtCore.QRect(10, 20, 391, 31))
        self.current_date_information.setMinimumSize(QtCore.QSize(391, 31))
        self.current_date_information.setObjectName("current_date_information")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 391, 771))
        self.groupBox.setObjectName("task_group_box")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(430, 70, 661, 761))
        self.tableWidget.setObjectName("sp_table")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.filter_date = QtWidgets.QComboBox(parent=Form)
        self.filter_date.setGeometry(QtCore.QRect(430, 20, 661, 31))
        self.filter_date.setObjectName("filter_date")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Tasks"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Service Provider"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Status"))
        
    def apply_styles(self):
        self.setStyleSheet("""
            QWidget {
                background-color: #f4f6f9;
                font-family: "Segoe UI", "Helvetica Neue", Arial, sans-serif;
                font-size: 14px;
            }

            QGroupBox {
                background-color: #ffffff;
                border: 2px solid #d0d7de;
                border-radius: 8px;
                margin-top: 20px;
                font-weight: bold;
                padding: 10px;
            }

            QLabel {
                color: #333333;
            }

            QLineEdit {
                background-color: #ffffff;
                border: 1px solid #d0d7de;
                border-radius: 6px;
                padding: 5px 10px;
            }

            QComboBox {
                background-color: #ffffff;
                border: 1px solid #d0d7de;
                border-radius: 6px;
                padding: 5px 10px;
            }

            QComboBox::drop-down {
                border-left: 1px solid #d0d7de;
            }

            QPushButton {
                background-color: #0078d7;
                color: #ffffff;
                border-radius: 6px;
                padding: 6px 14px;
                font-weight: bold;
            }

            QPushButton:disabled {
                background-color: #a0a0a0;
                color: #f0f0f0;
            }

            QPushButton:hover {
                background-color: #005a9e;
            }

            QTableWidget {
                background-color: #ffffff;
                border: 1px solid #d0d7de;
                border-radius: 8px;
                gridline-color: #e0e0e0;
                selection-background-color: #0078d7;
                selection-color: #ffffff;
            }

            QHeaderView::section {
                background-color: #f0f3f6;
                padding: 6px;
                border: 1px solid #d0d7de;
                font-weight: bold;
            }
        """)
